### ISSUE TITLE
tool used for recovery 

### ISSUE THREAD

**Issue by manfire** [cod3gen/sgminer-baikal#1]
I have giant B here, tell me witch tool and I upload the result

thx you

**Comment by cod3gen** [comment]
You can use Photorec which is included with testdisk. To get this you can install package by using command "sudo apt-get install testdisk" then run "photorec".  You need to attach and mount a USB memory stick with atleast 4GB, or 8GB depending on which SD card is on your miner

**Comment by manfire** [comment]
running at this moment, i come back sortly
