### ISSUE TITLE
Compiling x10 Error

### ISSUE THREAD

**Issue by samsonkight** [cod3gen/sgminer-baikal#10]
collect2: error: ld returned 1 exit status                                                                              
Makefile:912: recipe for target 'sgminer' failed                                                                        
make[2]: *** [sgminer] Error 1                                                                                          
make[2]: Leaving directory '/home/baikal/sgminer-baikal'                                                                
Makefile:1824: recipe for target 'all-recursive' failed                                                                 
make[1]: *** [all-recursive] Error 1                                                                                    
make[1]: Leaving directory '/home/baikal/sgminer-baikal'                                                                
Makefile:717: recipe for target 'all' failed                                                                            
make: *** [all] Error 2                                                                                                 
baikal@Baikal:~/sgminer-baikal$ cp /opt/scripta/bin/sgminer /opt/scripta/bin/sgminer_ORG                                
cp: cannot create regular file '/opt/scripta/bin/sgminer_ORG': Permission denied

**Comment by cod3gen** [comment]
sgminer have not been successfully compiled, you need to check why that is.
