### ISSUE TITLE
Error when run "autoreconf -fi && ./configure && make"

### ISSUE THREAD

**Issue by hieungueyn** [cod3gen/sgminer-baikal#12]
Hi

I have this error when run autoreconf -fi && ./configure && make as follow
configure.ac:25: installing './compile'                                                                                 
configure.ac:23: installing './missing'                                                                                 
Makefile.am: installing './depcomp'                                                                                     
./configure: line 2443: config.log: Permission denied                                                                   
./configure: line 2453: config.log: Permission denied

**Comment by cod3gen** [comment]
Not sure why this would happen. Have you followed all steps, and are you logged in as root? Try to run this command first, chmod 777 submodules/libusb-bk/config.log

**Comment by hieungueyn** [comment]
Hi
I have run chmod 777 submodules/libusb-bk/config.log but still same error. I run follow your all step by step

**Comment by hieungueyn** [comment]
I loged terminal with user/pass: baikal/baikal

**Comment by cod3gen** [comment]
Login as root; root/baikal

**Comment by hieungueyn** [comment]
I can not login with root/baikal. It say that login incorrect

**Comment by hieungueyn** [comment]
Hi code3gen

Thanks for your help. This my machine must be use putty to ssh into installing your firmware, although other my machine can install through terminal tab of baikal web interface.
Hope your other good new about OC Baikal X10, Giant B

Best regards,
