### ISSUE TITLE
Need Urgent help on how to run the binary sgminer

### ISSUE THREAD

**Issue by kumarfirmware** [cod3gen/sgminer-baikal#13]
Hi Team,

Good Morning. 

Your article and open source to rebuild of Baikal`s SG Miner for Giant X10 / N / B is a great help and excellent stuff.

How ever I have a problem in running this binary sgminer.

I have compiled and built it successfully the binary sgminer but how should I run it?

It does not run on its own, but the original sgminer binary runs on it own.

Do I need to provide any pool configuration or user name and password information manually?

Kindly help me as soon as possible.

In the web page I see the error as devices not running.

So can you please explain me after compiling and building the binary how do I need to run it successfully?

Any help in this will be highly appreciated.

Thanks,Regards,
Kumar.

**Comment by ZenoDiac** [comment]
@kumarfirmware Hmmmm according to the instructions you need to overwrite the default file with the file you just compiled, as in the last step.

@cod3gen  I am getting a "-bash: git: command not found error" after installing git with sudo apt-get install git. 
Screenshot: https://puu.sh/Bd0Fi/8ae5997ac2.png
I have tried sudo apt-get update. I can't seem to clone the repository. Any suggestions?

**Comment by cod3gen** [comment]
@ZenoDiac You need to allocate more memory.. Look further down in instructions..

@kumarfirmware check what @ZenoDiac said. Which baikal do you have?

**Comment by ZenoDiac** [comment]
@cod3gen Thanks man, it's working now perfectly. http://puu.sh/Bd3CA/064420e0ed.png

@kumarfirmware I think I ran into the same problem as you... Try using sudo screen -x sgminer. Once you press ctrl+c, use copy paste from the browser for sudo cp sgminer /opt/scripta/bin/sgminer. 
Execute it within about 5 seconds, otherwise sgminer will start again and you won't be able to overwrite. 
If you missed it, you need to start the session again and repeat till you get it (This worked for Giant B).

-Thanks again cod3gen for this code.

**Comment by kumarfirmware** [comment]
Hi @cod3gen, ZenoDiac,

Thanks a lot for your immediate reply. This means a lot and highly appreciated.

I have Baikal`s SG Miner for Giant X10.

I compiled the file successfully and generated sgminer file successfully and over written the default file with this and I restarted the miner because on power up the binary sgminer will start automatically.

Am I missing any important step here? kindly help. what is the sequence I am missing here?

on restart I see no devices running. But when I keep the original file and restart the device I see devices running. So I am missing a small step or sequence here. Can you please help me in this as soon as possible.

Thanks,Regards,
Kumar.

**Comment by cod3gen** [comment]
Sounds like your X10 is not compatible. What is your Date of Purchase on
the unit? There is no gain of using this miner btw, it only overclocks B's

Den søn. 12. aug. 2018, 20:57 skrev kumarfirmware <notifications@github.com

**Comment by kumarfirmware** [comment]
Hi @cod3gen,

Thanks a lot for your immediate reply.
I have brought Baikal`s SG Miner Giant X10 in 2017 December.
I did not do any changes to the code provided by you. I just compiled and build binary sgminer.
I copied it in the location /opt/scripta/bin/ and did a restart of the miner thats all.

1.Am I missing any step here ?
2.Do I need to execute the binary sgminer manually or it automatically gets executed on startup?
3. Do I need to do any specific code changes for X10?
4.what I am worried is why it does not run at all? It shows no devices running? This is my biggest concern.
5. Also original binary sgminer is 6,500KB, but the binary sgminer I got after compiling is 7,500KB. Is it a concern?
6. Also do I need to update the firmware Image for STM32?
7. The first goal for me is to make the binary sgminer run after buidling it successfully. why it is not running. Am I missing any step here? How to execute the sgminer built?

Kindly help me as soon as possible.

Thanks,Regards,
Kumar.

**Comment by kumarfirmware** [comment]
Hi @cod3gen, ZenoDiac,

Thanks a lot for your immediate reply.
I have brought Baikal`s SG Miner Giant X10 in 2017 December.
I did not do any changes to the code provided by you. I just compiled and build binary sgminer.
I copied it in the location /opt/scripta/bin/ and did a restart of the miner thats all.

1.Am I missing any step here ?
2.Do I need to execute the binary sgminer manually or it automatically gets executed on startup?
3. Do I need to do any specific code changes for X10?
4.what I am worried is why it does not run at all? It shows no devices running? This is my biggest concern.
5. Also original binary sgminer is 6,500KB, but the binary sgminer I got after compiling is 7,500KB. Is it a concern?
6. Also do I need to update the firmware Image for STM32?
7. The first goal for me is to make the binary sgminer run after buidling it successfully. why it is not running. Am I missing any step here? How to execute the sgminer built?

Kindly help me as soon as possible.

Thanks,Regards,
Kumar.

**Comment by cod3gen** [comment]
When you(sucessfully) copy over sgminer binaries to /opt/scripta/bin/ it should all run automatically. From the mining machines point of view, it still would think you are running the orginal sgminer from Baikal. 

This binary is slightly larger because it includes more algo`s in the sgminer side (does not help on Baikal, that requires firmware for the STM32 chip).

You can try to upgrade firmware, but if it shows no devices running, this sgminer may not work on your Miner.

**Comment by cod3gen** [comment]
I have now updated the tutorial for copying sgminer with a better way to ensure it is stopped.

**Comment by kumarfirmware** [comment]
Hi @cod3gen,

Thanks for your immediate reply.

So you are saying this software does not work for Baikal`s SG Miner Giant X10 and it works only for Giant B.

Any changes you can think of to this software which may make it work on Giant X10 at least basic stuff?

Is there a way then to get open source for Baikal`s SG Miner Giant X10? can you kindly help in this?

Thanks,Regards,
Kumar.

**Comment by cod3gen** [comment]
No, thats not what im saying. "on your Miner". It works on both my Giant X10 and Giant N. What reasons it does not work on yours i don`t know.

However, it only overclock`s Giant B. There are no gains of using this SGminer version on X10 or N

**Comment by kumarfirmware** [comment]
Hi @cod3gen,

Thanks for your immediate reply.

Ok fine I understood now what you meant.

I will try to send some screen shots for you to see if it can help you in quick check what might be the problem for the basic running. For sure I might be making some small basic mistake

Any thing I need to change in your code? Any #define or so? I did not do any code change just compiled and copied and restarted. Do you see any problems with this?

Did you do any code change to make it work on your Giant X10 or you ran as it is?

Thanks,Regards,
Kumar.

**Comment by cod3gen** [comment]
Should run fine as it is, you can change #define BAIKAL_CLK_DEF but it should run anyway so thats not the issue.

**Comment by kumarfirmware** [comment]
Hi @cod3gen,

Thanks for your immediate reply.

After generating binary file sgminer, I am taking winscp and deleting the original file and copying the successfully build file and restarting. Hope this should not create any problem.

correct me if this process is wrong.

I will send some screen shots for you to see if it can help you in quick check what might be the problem for the basic running.

Thanks,Regards,
Kumar.

**Comment by bastasie** [comment]
hello it says checking whether the C compiler works ...no
am using Baikal n+

**Comment by bastasie** [comment]
it compiled now but its giving only rejected blocks

**Comment by cod3gen** [comment]
Ive had reports of it not working on Giant N+ earlier, so it seems N+ is not compatible without doing changes to the code.

**Comment by getabaikal** [comment]
> Hi @cod3gen,
> 
> Thanks for your immediate reply.
> 
> After generating binary file sgminer, I am taking winscp and deleting the original file and copying the successfully build file and restarting. Hope this should not create any problem.
> 
> correct me if this process is wrong.
> 
> I will send some screen shots for you to see if it can help you in quick check what might be the problem for the basic running.
> 
> Thanks,Regards,
> Kumar.

hi Kumar, did you get your X10 functioning? I'm having similar issues.
