### ISSUE TITLE
Possible to replace Baikal FPGA's?

### ISSUE THREAD

**Issue by extro24** [cod3gen/sgminer-baikal#14]
Hi cod3gen

Baikal seems to be an Orange PI controlling an STM32 microcontroller controlling the Digital Encryption System BS91 hashing chips.  Is that about right?  

Would it be possible to substitute normal Xilinx FPGA's for the STM32 and BS91 chips?

To me it looks like driver-baikals.c is the file that communicates with the STM32.

-extro

**Comment by cod3gen** [comment]
Sure, the SGMiner can be used to control other solutions.. Its just a "frontend"(or maybe we should call it a proxy?), so you would only need to create a "driver" for that other solution. SGMiner in this case does more or less everything except creating kernels for the chips, it only tells STM32 which algo it should mine.
