### ISSUE TITLE
Bitcoin talk

### ISSUE THREAD

**Issue by bastasie** [cod3gen/sgminer-baikal#15]
sgminer 5.6.2-BK_cod3gen_MOD - Started: [2018-03-27 20:28:01] - [0 days 02:15:45]
--------------------------------------------------------------------------------
(5s):20.16K (avg):20.11Kh/s | A:392  R:0  HW:0  WU:3.088/m
ST: 1  SS: 27  NB: 88  LW: 8420  GF: 0  RF: 0
Connected to pool.supportxmr.com (stratum) diff 500K as user XXX
Block: 3516dd19...  Diff:0  Started: [22:42:41]  Best share: 556M
--------------------------------------------------------------------------------
 [U]SB management [P]ool management [S]ettings [D]isplay options [Q]uit
BKLU 0: 34C 200MHz [ASICS #32] | 6.670K/6.672Kh/s | A:125 R:0 HW:0 WU:1.002/m
BKLU 1: 33C 200MHz [ASICS #32] | 6.718K/6.721Kh/s | A:132 R:0 HW:0 WU:1.032/m
BKLU 2: 34C 200MHz [ASICS #32] | 6.718K/6.721Kh/s | A:135 R:0 HW:0 WU:1.054/m

I saw this post on bitcointalk. Congrats your project is working! I tried it and it gave me a similar screen to tgeabove but with rejected blocks only i connected to the same pool above. What could be wrong?

**Comment by cod3gen** [comment]
Monero forked, so its not possible to mine Monero(XMR).

**Comment by bastasie** [comment]
I have one more question
If chnage the control boards is it possible to mine monero? If thats possible could you share your email with me?

**Comment by cod3gen** [comment]
No, its not possible to mine Monero. You are restricted to regular Cryptonight or Cryptonight-lite
