### ISSUE TITLE
cryptonight v7

### ISSUE THREAD

**Issue by oliwerhun** [cod3gen/sgminer-baikal#16]
Hi! Can I rebuild sgminer on Baikal N70? If yes, can I mining cryptonight v7? Thanks! Regards!

**Comment by nasier88** [comment]
i want to know same thing.. can baikal n+ mining cv7

**Comment by hagopk** [comment]
any one can make changing on baikal BK-N OR N+OR N70 to mine CN v7 OR v8 MONERO ?THANKS

**Comment by getabaikal** [comment]
Of course it can't. Nobody cares. People are using FPGA's to do that.

**Comment by hagopk** [comment]
what do you think if this real  and firmware changing engineering ??? can or not possible or not ?
https://youtu.be/8ZpcSx2kqeo

**Comment by hagopk** [comment]
i think some engineer adding SGMiner  OR cg MINER ON THIS SD CARD OR INSTALLING UPGRADING FIRMWARE OF PI ZERO and that can be also by coding some text on files to add algo and divice can run . but who is that professional engineer can programm this
