### ISSUE TITLE
Unable to compile on Baikal N+

### ISSUE THREAD

**Issue by javijupra** [cod3gen/sgminer-baikal#19]
After adding swap memory, stuck compiling shabal.o
No errors or warnings, just stuck.
On previous issues, I read it's a known fact that the N+ won't compile. I'll try to dig deeper.

```
make[2]: Entering directory '/home/baikal/sgminer-baikal/sph'
  CC       shavite.o
  CC       skein.o
  CC       sha2.o
  CC       sha2big.o
  CC       fugue.o
  CC       hamsi.o
  CC       panama.o
  CC       shabal.o
```
I'll happily research what's needed to change in code, might need some guidance.

**Comment by alongnew** [comment]
you have to swap your memory
