### ISSUE TITLE
Baikal GIANT N +

### ISSUE THREAD

**Issue by alongnew** [cod3gen/sgminer-baikal#20]
When you compile sgminer for baikal giant N+ to mine cn-heavy and cn-v8?

**Comment by smannering** [comment]
Is it possible to update the N+ to mine later versions of teh CN Algo?

**Comment by alongnew** [comment]
want to ask how you can take sgminer in the form of prebuild is there for N +? because the code you make is for BKN

**Comment by osirus466** [comment]
> When you compile sgminer for baikal giant N+ to mine cn-heavy and cn-v8?

Were you able to get the baikal to mine cnV8?

**Comment by osirus466** [comment]
> want to ask how you can take sgminer in the form of prebuild is there for N +? because the code you make is for BKN

Were you able to get the Baikal mining cnv8?

**Comment by smannering** [comment]
Never got it to work :-(

**Comment by cod3gen** [comment]
Its not possible to use N+ to mine the newer algoritms
