### ISSUE TITLE
Does not work at 70

### ISSUE THREAD

**Issue by Wildimon** [cod3gen/sgminer-baikal#22]
Hello to everyone in the topic!!! Thank you for Your work! This is a very good and great job!
I'm sorry your code doesn't work on the N-series.(i have N70)
The values in the driver-baikal files may be incorrect. My devices, don't initialise and don't works in this code. Help me, please.
Thank for good jobs. Good luck!

**Comment by Wildimon** [comment]
How to improve my help in to this good project?

**Comment by cod3gen** [comment]
Only works with the early or first N series miner
