### ISSUE TITLE
baikal-N240 An error occurred

### ISSUE THREAD

**Issue by John-xmrig** [cod3gen/sgminer-baikal#24]
submodules/libusb-bk/libusb/.libs/libusb-1.0.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
Makefile:912: recipe for target 'sgminer' failed
make[2]: *** [sgminer] Error 1
make[2]: Leaving directory '/root/sgminer-baikal'
Makefile:1824: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/sgminer-baikal'
Makefile:717: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cod3gen** [comment]
Does not work on N240
